name: checkout
description: like actions/checkout, but always checkout .github/ ydb/ci from main branch
inputs:
  ref:
    description: >
      The branch, tag or SHA to checkout. When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that
      event.  Otherwise, uses the default branch.
    required: false
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    required: false
  sparse-checkout:
    description: >
      Do a sparse checkout on given patterns.
      Each pattern should be separated with new lines.
    required: false
runs:
  using: composite
  steps:
    - name: checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        path: ${{ inputs.path }}
        sparse-checkout: ${{ inputs.sparse-checkout }}
        
    - name: checkout .github, ydb/ci
      uses: actions/checkout@v4
      with:
        ref: main
        path: repo-main
        sparse-checkout: |
          .github/actions
          .github/scripts
          ydb/ci
      
    - name: replace repository .github, ydb/ci
      shell: bash
      run: |
        rsync -av --delete repo-main/.github/actions/ .github/actions/
        rsync -av --delete repo-main/.github/scripts/ .github/scripts/
        rsync -av --delete repo-main/ydb/ci/ ydb/ci/
        rm -rf repo-main/
