name: Ya-Build-and-Test-Provisioned

on:
  workflow_dispatch:
    inputs:
      build_target:
        type: string
        default: "ydb/"
        description: "limit build and test to specific target"
      build_preset:
        type: choice
        default: "relwithdebinfo"
        description: "Build preset"
        options:
          - relwithdebinfo
          - release-asan
          - release-tsan
      test_size:
        type: choice
        default: "all"
        description: "test size to run"
        options:
          - small
          - small-medium
          - all
      run_build:
        type: boolean
        default: true
        description: "run build"
      run_tests:
        type: boolean
        default: true
        description: "run tests"
      test_threads:
        type: string
        default: "28"
        description: "Test threads count"
      link_threads:
        type: string
        default: "8"
        description: "link threads count"
      runner_label:
        type: string
        default: "ya-make"
        description: "runner label"
  workflow_call:
    inputs:
      build_target:
        type: string
      build_preset:
        type: string
      test_size:
        type: string
        default: "all"
      run_build:
        type: boolean
        default: true
      run_tests:
        type: boolean
        default: true
      test_threads:
        type: string
        default: "28"
        description: "Test threads count"
      link_threads:
        type: string
        default: "8"
        description: "link threads count"
      runner_label:
        type: string
        default: "ya-make"

jobs:
  main:
    uses: ./.github/workflows/build_and_test_ya.yml
    with:
      runner_kind: provisioned
      runner_label: ${{ inputs.runner_label }}
      build_target: ${{ inputs.build_target }}
      build_preset: ${{ inputs.build_preset }}
      run_build: ${{ inputs.run_build }}
      run_tests: ${{ inputs.run_tests }}
      test_size: ${{ inputs.test_size }}
      link_threads: ${{ inputs.link_threads }}
      test_threads: ${{ inputs.test_threads }}
    secrets: inherit
